# Generated by Django 5.0 on 2023-12-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
    ]
